resources: 
- db/
- message-broker/
- nginx/

#Using Patches

##  Replace The NO. Of Replicas  - Method  JSON 6902 Patch
patches:
- target: 
    kind: Deployment
    name: nginx-deployment
  patch: |-
    - op: replace 
      path: /spec/replicas
      value: 5


##  Second Method - Strategic Merge Patch

patches: 
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata: 
        name: nginx-deployment
      spec: 
        replicas: 6



## replace labels

patches:
- target: 
    kind: Deployment
    name: nginx-deployment
  patch: |-
    - op: replace 
      path: /spec/template/metadata/labels/component
      value:  mayank



##adding the new labels


- target: 
    kind: Deployment
    name: nginx-deployment
  patch: |-
    - op: add 
      path: /spec/template/metadata/labels/org
      value: prod
